server:
 port: 9596
 
spring:
 application:
  name: ap-service2-app
 profiles:
  active: production
 jackson:
  serialization: 
    indent-output: true
 
management:
 endpoints:
  web:
    exposure:
      include: "*"
 enpoint:
  health:
    show-details: always 
eureka:
 instance:
  ip-address: true
  metadata-map:
    user.name: ${spring.security.user.name}
    user.password: ${spring.security.user.password}
 client:
  enabled: true
  register-with-eureka: true
  service-url: 
    default-zone: http://localhost:8761/eureka